# Generated by Django 5.0.3 on 2024-03-17 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CARDANO MAZE', max_length=20)),
                ('quantity_mined', models.PositiveIntegerField(default=0)),
                ('time_clicked', models.DateTimeField()),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('mineral_extracted', models.CharField(max_length=50)),
                ('extraction_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
