# Generated by Django 5.0.3 on 2024-03-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mining',
            name='mineral_extracted',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mining',
            name='quantity_mined',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
