# Generated by Django 5.0.3 on 2024-03-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_alter_mining_mineral_extracted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mining',
            name='first_clicked',
            field=models.BooleanField(default=True),
        ),
    ]
