# Generated by Django 5.0.3 on 2024-03-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_mining_first_clicked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mining',
            old_name='first_clicked',
            new_name='first_click',
        ),
    ]
