# Generated by Django 5.0.3 on 2024-03-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0005_mining_end_time_mining_remaining_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mining',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='mining',
            name='remaining_time',
        ),
    ]
