# Generated by Django 5.0.3 on 2024-03-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0006_remove_mining_end_time_remove_mining_remaining_time'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mining',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.telegramuser'),
        ),
    ]
