# Generated by Django 5.0.3 on 2024-03-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0007_mining_user'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mining',
            name='quantity_mined',
            field=models.DecimalField(decimal_places=2, default='100.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mining',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coin', to='telegram.telegramuser'),
        ),
    ]
