# Generated by Django 5.0.3 on 2024-03-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramuser_currency_alter_telegramuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
