# Generated by Django 5.0.3 on 2024-03-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_currency',
            field=models.CharField(default='ADA', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='fiat_amount',
            field=models.DecimalField(decimal_places=2, default='3.00', max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='fiat_currency',
            field=models.CharField(default='usd', max_length=50),
        ),
    ]
